### PR TITLE
Use NuGet for Newtonsoft.JSON

### PR DESCRIPTION
**Pull request by hzalaz**
@siacomuzzi @dschenkelman please review. Using NuGet instead of local copy for JSON dependency.
Tries to address #13

### CODE REVIEW

**Comment by siacomuzzi** [comment]
Thanks! It would be great if you could update the samples too.

**Comment by dschenkelman** [comment]
Just talked with Zala. It looks like this is pointing to NuGet package but it is actually Xamarin component.

**Comment by dschenkelman** [comment]
:+1:

**Comment by hzalaz** [comment]
Samples updated

**Comment by siacomuzzi** [comment]
Available at 0.4.3 (pending approval)

**Pull request merged**
